# Generated by Django 6.1.1 on 2026-09-13 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housemate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('recurrence', models.CharField(choices=[('FIXED', 'Fixed schedule'), ('INTERVAL', 'Interval since last done')], default='INTERVAL', max_length=8)),
                ('interval_days', models.PositiveIntegerField(help_text='Days between occurrences. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('next_due', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_due', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('interval_days__gte', 1)), name='chore_interval_days_at_least_1')],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed_on', models.DateField()),
                ('was_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.chore')),
                ('housemate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='chores.housemate')),
            ],
            options={
                'ordering': ['-completed_on', '-created_at'],
            },
        ),
    ]
